CREATE INDEX users_role_status_idx ON users (role, status);
CREATE INDEX refresh_tokens_user_id_idx ON refresh_tokens (user_id);
CREATE INDEX refresh_tokens_expires_at_idx ON refresh_tokens (expires_at);
CREATE INDEX sellers_owner_user_id_idx ON sellers (owner_user_id);
CREATE INDEX stores_slug_idx ON stores (slug);
CREATE INDEX domains_hostname_idx ON domains (hostname);
CREATE INDEX seller_agents_user_status_idx ON seller_agents (user_id, status);
CREATE INDEX seller_agents_seller_status_idx ON seller_agents (seller_id, status);
CREATE INDEX customers_user_id_idx ON customers (user_id);
CREATE INDEX seller_customers_customer_id_idx ON seller_customers (customer_id);
CREATE INDEX customer_addresses_customer_id_idx ON customer_addresses (customer_id);
CREATE INDEX categories_seller_status_idx ON categories (seller_id, status);
CREATE INDEX brands_seller_id_idx ON brands (seller_id);
CREATE INDEX products_seller_status_idx ON products (seller_id, status);
CREATE INDEX products_category_id_idx ON products (category_id);
CREATE INDEX products_brand_id_idx ON products (brand_id);
CREATE INDEX product_tags_tag_idx ON product_tags (tag);
CREATE INDEX product_variants_product_id_idx ON product_variants (product_id);
CREATE INDEX product_media_product_id_idx ON product_media (product_id);
CREATE INDEX inventory_seller_product_idx ON inventory (seller_id, product_id);
CREATE INDEX inventory_movements_seller_created_idx ON inventory_movements (seller_id, created_at);
CREATE INDEX carts_customer_seller_idx ON carts (customer_id, seller_id);
CREATE INDEX cart_items_cart_id_idx ON cart_items (cart_id);
CREATE INDEX orders_seller_status_idx ON orders (seller_id, status);
CREATE INDEX orders_customer_status_idx ON orders (customer_id, status);
CREATE INDEX order_items_order_id_idx ON order_items (order_id);
CREATE INDEX order_status_history_order_id_idx ON order_status_history (order_id);
CREATE INDEX payments_order_id_idx ON payments (order_id);
CREATE INDEX payments_seller_status_idx ON payments (seller_id, status);
CREATE INDEX payment_events_provider_created_idx ON payment_events (provider, created_at);
CREATE INDEX shipping_methods_seller_status_idx ON shipping_methods (seller_id, status);
CREATE INDEX shipments_order_id_idx ON shipments (order_id);
CREATE INDEX shipments_seller_status_idx ON shipments (seller_id, status);
CREATE INDEX tax_rules_country_region_idx ON tax_rules (country, region);
CREATE INDEX return_requests_seller_status_idx ON return_requests (seller_id, status);
CREATE INDEX refunds_seller_status_idx ON refunds (seller_id, status);
CREATE INDEX commission_rules_scope_priority_idx ON commission_rules (scope_type, priority);
CREATE INDEX commissions_seller_created_idx ON commissions (seller_id, created_at);
CREATE INDEX wallets_seller_id_idx ON wallets (seller_id);
CREATE INDEX wallet_transactions_wallet_created_idx ON wallet_transactions (wallet_id, created_at);
CREATE INDEX payout_requests_seller_status_idx ON payout_requests (seller_id, status);
CREATE INDEX reviews_product_status_idx ON reviews (product_id, status);
CREATE INDEX support_tickets_seller_status_idx ON support_tickets (seller_id, status);
CREATE INDEX support_tickets_customer_status_idx ON support_tickets (customer_id, status);
CREATE INDEX support_ticket_messages_ticket_created_idx ON support_ticket_messages (ticket_id, created_at);
CREATE INDEX conversations_seller_customer_idx ON conversations (seller_id, customer_id);
CREATE INDEX messages_conversation_created_idx ON messages (conversation_id, created_at);
CREATE INDEX notifications_user_read_idx ON notifications (user_id, read_at);
CREATE INDEX subscriptions_seller_status_idx ON subscriptions (seller_id, status);
CREATE INDEX seller_verifications_seller_status_idx ON seller_verifications (seller_id, status);
CREATE INDEX fraud_events_created_idx ON fraud_events (created_at);
CREATE INDEX audit_logs_actor_created_idx ON audit_logs (actor_user_id, created_at);
CREATE INDEX audit_logs_seller_created_idx ON audit_logs (seller_id, created_at);
CREATE INDEX background_jobs_queue_status_idx ON background_jobs (queue, status, available_at);
